version: '3'

services:
  remote_logger_rails:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    env_file:
      - 'docker/web/.env.web'
    volumes:
      # Named volume
      - DataRemoteLogger:/database

volumes:
  DataRemoteLogger:
